# config/_default/languages.en.toml

title = "Karthikeyan Krish"

[params.author]
name = "Karthikeyan Krish"
image = "img/author.jpeg"
headline = "Technical Sales and Marketing Professional"
bio = "Hello, My name is Karthik. I am a Technology learner. Currently working as a Senior Systems Engineer (Presales) handling South India, Sri Lanka and Maldives Enterprise vertical for Extreme Networks."
links = [
  { twitter = "https://twitter.com/iamkarthikkrish" },
  { linkedin = "https://linked.com/in/mkarthikeyan" },
  { github = "https://github.com/indhradhanush" }
]

