# config/_default/menus.en.toml

[[main]]
  name = "About Me"
  pageRef = "/about/"
  weight = 10
  [main.params]
    icon = "list"
    showName = true

[[main]]
  name = "Publications"
  pageRef = "/pubs/"
  weight = 20
  [main.params]
    icon = "lightbulb"
    showName = true

[[main]]
  name = "Resume"
  pageRef = "/resume/"
  weight = 30
  [main.params]
    icon = "google-scholar"
    showName = true

[[main]]
  name = "Blog"
  url = "https://whnetwork.wordpress.com/"
  weight = 40
  [main.params]
    icon = "blogger"
    showName = true
    target = "_blank"

[[main]]
  name = "GitHub"
  url = "https://github.com/indhradhanush"
  weight = 50
  [main.params]
    icon = "github"
    showName = true
    target = "_blank"

[[main]]
  name = "Contact"
  pageRef = "/contact/"
  weight = 60
  [main.params]
    icon = "coffee"
    showName = true

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Privacy"
  pageRef = "privacy"

